feign:
  hystrix:
    enabled: true
eureka:
  #server:
  ##  enable-self-preservation: false
  # eviction-interval-timer-in-ms: 10
  #peer-eureka-status-refresh-time-interval-ms: 10
  instance:
    instance-id: shavedog-admin.com
  client:
    # lease-expiration-duration-in-seconds: 60 #服务过期设置，超过这个时间没有接收到心跳EruekaServer就会将这个实例剔除
    #lease-renewal-interval-in-seconds: 60 #服务刷新时间配置每隔这个时间就会主动心跳一次
    service-url:
      defaultZone: http://mingyuan:mingyuan@eureka.com:7001/eureka
spring:
  application:
    name: shavedog-provider-item
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://inheart.club:3306/shavedog?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: mysqladmin
    dbcp2:
      min-idle: 5
      max-total: 5
      initial-size: 3
      max-wait-millis: 100
  profiles:
    active: dev
management:
  endpoint:
    info:
      enabled-by-default: false
      enabled: true
server:
  port: 8001